// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `invalid_config`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativeRustBoxEngine>>
abstract class NativeRustBoxEngine implements RustOpaqueInterface {
  static Future<NativeRustBoxEngine> create({required String configToml}) =>
      RustLib.instance.api.crateApiEngineNativeRustBoxEngineCreate(
        configToml: configToml,
      );

  Future<void> reload({required String configToml});

  Future<void> shutdown();

  Future<BridgeEngineSnapshot> snapshot();

  Future<void> start();

  Future<void> stop();
}

class BridgeEngineSnapshot {
  final BridgeEngineState state;
  final BigInt generation;
  final BigInt inboundCount;
  final BigInt outboundCount;

  const BridgeEngineSnapshot({
    required this.state,
    required this.generation,
    required this.inboundCount,
    required this.outboundCount,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      generation.hashCode ^
      inboundCount.hashCode ^
      outboundCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEngineSnapshot &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          generation == other.generation &&
          inboundCount == other.inboundCount &&
          outboundCount == other.outboundCount;
}

enum BridgeEngineState { created, prepared, running, stopping, stopped, failed }

class BridgeError implements FrbException {
  final BridgeErrorKind kind;
  final String message;

  const BridgeError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum BridgeErrorKind { invalidConfig, invalidState, unavailable, runtime }
