//! Machine-readable contract for the native TOML and JSON configuration.

#[cfg(feature = "schema-generation")]
use crate::SUPPORTED_SCHEMA_VERSION;

/// Checked-in JSON Schema shared by native TOML and native JSON inputs.
pub const NATIVE_CONFIG_SCHEMA_JSON: &str = include_str!("../schema/rustbox-config-v1.schema.json");

/// Returns the versioned native configuration contract.
///
/// The returned schema describes document shape and scalar constraints. Full
/// semantic validation, including reference resolution and platform support,
/// remains the responsibility of the normal configuration compiler.
pub const fn native_config_schema_json() -> &'static str {
    NATIVE_CONFIG_SCHEMA_JSON
}

/// Generates the canonical JSON Schema from the native deserialization model.
#[cfg(feature = "schema-generation")]
pub fn generate_native_config_schema() -> serde_json::Value {
    use crate::document::ConfigDocument;
    use schemars::generate::SchemaSettings;
    use serde_json::{Value, json};

    let schema = SchemaSettings::draft2020_12()
        .for_deserialize()
        .into_generator()
        .into_root_schema_for::<ConfigDocument>();
    let mut value = serde_json::to_value(schema).expect("serialize generated config schema");
    let root = value
        .as_object_mut()
        .expect("generated config schema must be an object");
    root.insert(
        "$id".to_string(),
        Value::String(format!(
            "https://loafman1120.github.io/RustBox/schema/rustbox-config-v{SUPPORTED_SCHEMA_VERSION}.schema.json"
        )),
    );
    root.insert(
        "title".to_string(),
        Value::String(format!(
            "RustBox native configuration v{SUPPORTED_SCHEMA_VERSION}"
        )),
    );
    root.insert(
        "description".to_string(),
        Value::String(
            "Structural contract shared by RustBox native TOML and JSON configuration files."
                .to_string(),
        ),
    );
    root.insert(
        "$comment".to_string(),
        Value::String(
            "Generated from Rust deserialization types; do not edit this file manually."
                .to_string(),
        ),
    );
    root.insert(
        "x-rustbox-schema-version".to_string(),
        json!(SUPPORTED_SCHEMA_VERSION),
    );
    value
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::SUPPORTED_SCHEMA_VERSION;

    #[test]
    fn embedded_schema_matches_supported_version() {
        let schema: serde_json::Value =
            serde_json::from_str(native_config_schema_json()).expect("valid embedded schema");
        assert_eq!(schema["x-rustbox-schema-version"], SUPPORTED_SCHEMA_VERSION);
        assert_eq!(
            schema["properties"]["schema_version"]["const"],
            SUPPORTED_SCHEMA_VERSION
        );
    }

    #[cfg(feature = "schema-generation")]
    #[test]
    fn checked_in_schema_matches_generated_contract() {
        let embedded: serde_json::Value =
            serde_json::from_str(native_config_schema_json()).expect("valid embedded schema");
        assert_eq!(embedded, generate_native_config_schema());
    }

    #[cfg(feature = "schema-generation")]
    #[test]
    fn generated_contract_documents_root_sections_and_secrets() {
        let schema = generate_native_config_schema();
        for field in [
            "schema_version",
            "observability",
            "inbounds",
            "outbounds",
            "endpoints",
            "dns",
            "rule_sets",
            "routes",
        ] {
            assert!(
                schema["properties"][field]["description"].is_string(),
                "root field `{field}` must have a description"
            );
        }
        assert_sensitive_properties_are_write_only(&schema);
    }

    #[cfg(feature = "schema-generation")]
    fn assert_sensitive_properties_are_write_only(value: &serde_json::Value) {
        let Some(object) = value.as_object() else {
            return;
        };
        if let Some(properties) = object
            .get("properties")
            .and_then(serde_json::Value::as_object)
        {
            for (name, property) in properties {
                if matches!(
                    name.as_str(),
                    "password" | "private_key" | "pre_shared_key" | "client_private_key_pem"
                ) {
                    assert_eq!(
                        property["writeOnly"], true,
                        "sensitive property `{name}` must be writeOnly"
                    );
                }
            }
        }
        for child in object.values() {
            match child {
                serde_json::Value::Array(values) => {
                    for value in values {
                        assert_sensitive_properties_are_write_only(value);
                    }
                }
                serde_json::Value::Object(_) => {
                    assert_sensitive_properties_are_write_only(child);
                }
                _ => {}
            }
        }
    }
}
